services:
  db-wiki:
    environment:
      MARIADB_ROOT_PASSWORD: 
      MARIADB_DATABASE: 
      MARIADB_USER: 
      MARIADB_PASSWORD: 
  app-wiki:
    environment:
      DB_USER:
      DB_PASS: 
      DB_NAME: